#ifndef INCLUDE_INTERFACES_FSI_DIRUTILS_WINDOWS_H_
#define INCLUDE_INTERFACES_FSI_DIRUTILS_WINDOWS_H_

#ifdef __cplusplus
# 	define __FSI_DIRUTILS_WINDOWS_CPP_OPEN 		extern "C" {
# 	define __FSI_DIRUTILS_WINDOWS_CPP_CLOSE 	}
#else
# 	define __FSI_DIRUTILS_WINDOWS_CPP_OPEN
# 	define __FSI_DIRUTILS_WINDOWS_CPP_CLOSE
#endif // __cplusplus

__FSI_DIRUTILS_WINDOWS_CPP_OPEN

// TODO:
// WINDOWS IMPLEMENTATION OF DIR UTILS ( POSIX )

__FSI_DIRUTILS_WINDOWS_CPP_CLOSE

#undef __FSI_DIRUTILS_WINDOWS_CPP_OPEN
#undef __FSI_DIRUTILS_WINDOWS_CPP_CLOSE

#endif  // INCLUDE_INTERFACES_FSI_DIRUTILS_WINDOWS_H_
